services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-1234qwer%}
      - TZ=Asia/Shanghai  # 东八区时区
      # 基础编码配置（无需额外文件）
      - MYSQL_CHARACTER_SET_SERVER=utf8mb4
      - MYSQL_COLLATION_SERVER=utf8mb4_general_ci
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - shared-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD:-1234qwer%}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6-alpine
    container_name: redis
    restart: always
    environment:
      - TZ=Asia/Shanghai  # 东八区时区
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - shared-network

volumes:
  mysql-data:
  redis-data:

networks:
  shared-network:
    external: true