name: Daily Notify
on:
  schedule:
    - cron: '0 2 * * *'
jobs:
  Notify-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
      - run: npm ci
      - name: Run node scripts
        run: node docs/.vuepress/public/notify/daily.js --token ${{ secrets.PUSHPLUS_TOKEN }}
      - run: echo "run success"
