name: Daily Notify
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  schedule:
    - cron: '20 11 * * *'
jobs:
  Notify-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
      - name: Run node scripts
        run: node docs/.vuepress/public/notify/daily.js --token ${{ secrets.PUSHPLUS_TOKEN }}
      - run: echo "run success"
     
