name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Node.js 23
      uses: actions/setup-node@v4
      with:
        node-version: '23'

    - name: Install pnpm
      uses: pnpm/action-setup@v2  # 安装 pnpm
      with:
        version: 10  # 指定 pnpm 版本

    - name: Install dependencies
      run: pnpm install  # 使用 pnpm 安装依赖

    - name: Build VuePress site
      run: pnpm run docs:build  # 使用 pnpm 执行构建脚本

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist