name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Set up Node.js 18
      uses: actions/setup-node@v4  # 使用最新版本的 setup-node
      with:
        node-version: '18'  # 指定 Node.js 版本为 18

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        BUILD_SCRIPT: yarn && yarn docs:build
        BUILD_DIR: dist