name: 每周自动打标签（原生Git版）
on:
  schedule:
    - cron: '0 8 * * 0'  # 北京时间16:00
  workflow_dispatch:

jobs:
  create-weekly-tag:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 拉取所有历史
          token: ${{ secrets.GITHUB_TOKEN }}  # 用于推送标签

      - name: 配置Git身份
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: 生成标签名称（北京时间）
        run: |
          TAG_NAME="weekly-$(TZ='Asia/Shanghai' date +%Y%m%d)"
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

      - name: 检查标签是否存在，不存在则创建并推送
        run: |
          # 检查远程是否存在该标签
          if git ls-remote --exit-code --tags origin ${{ env.TAG_NAME }}; then
            echo "标签 ${{ env.TAG_NAME }} 已存在，跳过"
          else
            # 创建带注释的标签
            git tag -a ${{ env.TAG_NAME }} -m "每周快照: $(TZ='Asia/Shanghai' date +%Y-%m-%d)"
            # 推送标签到远程
            git push origin ${{ env.TAG_NAME }}
            echo "标签 ${{ env.TAG_NAME }} 已创建并推送"
          fi
